name: qr_generator
description: QR generator

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  intl: ^0.18.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/img/logo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/img/logo.png"